name: chocolatine
run-name: ${{ github.actor }} asking for main action
on: [push, pull_request]
jobs:

  check_coding_style:
    runs-on: ubuntu-latest
    name: check_coding_style
    container: ghcr.io/epitech/coding-style-checker:latest
    steps:

      - name: Checkout GH repository
        uses:  actions/checkout@v3
        with:
          repository: ''

      - name: run conding-style.sh
        run: coding_style.sh . .

      - name: Display banana report
        run: cat coding-style-reports.log

      - name: report banana result
        run: |
          NB_ERROR=$(cat coding-style-reports.log | wc -l)
          if [ $NB_ERROR -gt 0 ]; then
            ERRORS=$(cat coding-style-reports.log);
              echo "Banana found $NB_ERROR error(s)"
              echo "$ERRORS"
              exit 1
          fi
          echo "Everything is good ! Keep on coding !"
          exit 0
