name: repository_size
run-name: ${{ github.actor }} asking for main action
on: push
jobs:

  repository_size:
    runs-on: ubuntu-latest
    steps:
      - uses:  actions/checkout@v3
        with:
          repository: ''
      - run: echo ${GITHUB_REF##*/}
      - run: du -skh --exclude=".git"