name: repository_size
run-name: ${{ github.actor }} asking for mirroring
on: [push, delete]
jobs:

  to_github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:EpitechPromo2027/B-DOP-200-BDX-2-1-chocolatine-tom.mendy.git
          ssh_private_key:
            ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
